name: cogmem-dev
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: cogmem_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cogmem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cogmem_default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cogmem_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cogmem_default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    name: cogmem_redis_data
  postgres_data:
    name: cogmem_postgres_data
  # pgvector_data:

networks:
  cogmem_default:
    name: cogmem_default