# CogMem Configuration with ChromemGo and OpenAI

# Logging Configuration
log:
  # Log level can be "debug", "info", "warn", or "error"
  level: "debug"
  # Format can be "text" or "json"
  format: "text"

# LTM (Long-Term Memory) Configuration
ltm:
  # Use ChromemGo as the vector storage backend
  type: "chromemgo"
  
  # ChromemGo (Vector DB) Configuration
  chromemgo:
    url: "http://localhost:8080"
    collection: "memories"
    dimensions: 1536

# Scripting Configuration
scripting:
  # Paths to directories containing Lua scripts
  paths:
    - "./scripts/mmu"
    - "./scripts/reflection"
  # Scripting engine settings
  engine:
    enable_sandboxing: true
    script_timeout_ms: 1000
    max_memory_mb: 100

# MMU (Memory Management Unit) Configuration
mmu:
  # Enable Lua hooks for memory operations
  enable_lua_hooks: true

# Reasoning Engine Configuration
reasoning:
  # Use OpenAI for reasoning and embeddings
  provider: "openai"
  openai:
    # Get API key from environment variable
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-4"
    embedding_model: "text-embedding-3-small"
    max_tokens: 1000
    temperature: 0.7

# Reflection Configuration
reflection:
  # Enable reflection process
  enabled: true
  # Number of interactions between reflection cycles
  trigger_frequency: 5
  # Maximum number of memories to analyze
  max_memories_to_analyze: 20
  # Model to use for analysis (empty uses default)
  analysis_model: ""
  # Temperature for analysis (lower for more focus)
  analysis_temperature: 0.3