# CogMem Configuration Example

# Logging Configuration
log:
  # Log level can be "debug", "info", "warn", or "error"
  level: "info"
  # Format can be "text" or "json"
  format: "text"

# LTM (Long-Term Memory) Configuration
ltm:
  # Type can be "sqlstore", "kv", "chromemgo", "mock"
  type: "mock"
  
  # SQL Store Backend Configuration
  sqlstore:
    # Driver can be "postgres" or "sqlite"
    driver: "sqlite"
    sqlite:
      path: "./data/cogmem.db"
    postgres:
      dsn: "postgres://postgres:postgres@localhost:5432/cogmem?sslmode=disable"
  
  # KV (Key-Value) Backend Configuration
  kv:
    # Provider can be "boltdb", "redis", or "postgres_hstore"
    provider: "boltdb"
    boltdb:
      path: "./data/cogmem.bolt.db"
    redis:
      addr: "localhost:6379"
      password: ""
      db: 0
    postgres_hstore:
      dsn: "postgres://postgres:postgres@localhost:5432/cogmem?sslmode=disable"
  
  # Vector Database Configuration
  vector:
    # Provider can be "postgres", "milvus", or "weaviate" or "chromemgo"
    provider: "postgres"
    postgres:
      dsn: "postgres://postgres:postgres@localhost:5432/cogmem?sslmode=disable"
    milvus:
      addr: "localhost:19530"
    weaviate:
      addr: "localhost:8080"
    chromemgo:
      url: "http://localhost:8080"
      collection: "memories"
      dimensions: 1536

  # Graph Database Configuration
  graph:
    # Provider can be "neo4j", "dgraph", or "postgres"
    provider: "postgres"
    neo4j:
      uri: "bolt://localhost:7687"
      username: "neo4j"
      password: "password"
    dgraph:
      addr: "localhost:9080"
    postgres:
      dsn: "postgres://postgres:postgres@localhost:5432/cogmem?sslmode=disable"

# Scripting Configuration
scripting:
  # Paths to directories containing Lua scripts
  paths:
    - "./scripts/mmu"
    - "./scripts/reflection"
  # Scripting engine settings
  engine:
    enable_sandboxing: true
    script_timeout_ms: 1000
    max_memory_mb: 100

# MMU (Memory Management Unit) Configuration
mmu:
  # Enable Lua hooks for memory operations
  enable_lua_hooks: true

# Reasoning Engine Configuration
reasoning:
  # Provider can be "openai", "anthropic", or "mock"
  provider: "openai"
  openai:
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-4"
    embedding_model: "text-embedding-3-small"
    max_tokens: 1000
    temperature: 0.7
  anthropic:
    api_key: "${ANTHROPIC_API_KEY}"
    model: "claude-3-opus-20240229"
    max_tokens: 1000
    temperature: 0.7

# Reflection Configuration
reflection:
  # Enable reflection process
  enabled: true
  # Number of interactions between reflection cycles
  trigger_frequency: 10
  # Maximum number of memories to analyze
  max_memories_to_analyze: 50
  # Model to use for analysis (empty uses default)
  analysis_model: ""
  # Temperature for analysis (lower for more focus)
  analysis_temperature: 0.3