# CogMem Configuration with Mock Backend
# Uses an in-memory mock backend for testing

# Logging Configuration
log:
  level: "debug"
  format: "text"

# LTM (Long-Term Memory) Configuration
ltm:
  # Use mock store for testing/demo
  type: "mock"

# Scripting Configuration
scripting:
  # Paths to directories containing Lua scripts
  paths:
    - "./scripts/mmu"
    - "./scripts/reflection"
  # Scripting engine settings
  engine:
    enable_sandboxing: true
    script_timeout_ms: 1000
    max_memory_mb: 100

# MMU (Memory Management Unit) Configuration
mmu:
  # Enable Lua hooks for memory operations
  enable_lua_hooks: true
  # Hook scripts for various memory operations
  hooks:
    # Script for customizing memory operations
    custom: "./scripts/mmu/custom_hooks.lua"
    # Script for embedding generation
    embedding: "./scripts/mmu/embedding_hooks.lua"
    # Script for filtering memory retrieval
    retrieval_filter: "./scripts/mmu/retrieval_filter.lua"
  # Retrieval configuration
  retrieval:
    max_results: 10

# Reasoning Engine Configuration
reasoning:
  # Use mock provider for reasoning (no external dependencies)
  provider: "mock"
  # MockEngine configuration
  mock:
    # Default response for queries
    default_response: "This is a response from the mock reasoning engine with some helpful information about the query."
    # Specific canned responses for certain inputs
    responses:
      "help": "I'm here to assist with memory management. You can store memories, retrieve them, and ask questions."
      "memory": "Memory is the ability to store and recall information. In CogMem, memories are stored in the LTM system."
      "CogMem": "CogMem is a cognitive memory system with multiple storage backends for long-term memory."
    # Response delay simulation in milliseconds (0 for no delay)
    response_delay_ms: 100

# Reflection Configuration
reflection:
  # Enable reflection process
  enabled: true
  # Number of interactions between reflection cycles
  trigger_frequency: 5
  # Maximum number of memories to analyze
  max_memories_to_analyze: 20